### PR TITLE
Port to Julia 1.5

### PR DESCRIPTION
**Pull request by serenity4**
Hi,

I recently reworked the package to work better with Julia 1.5 using the Artifact system and a Project.toml. I didn't test if it works for earlier versions. I also started to work on some convenience functions & abstractions. I don't know yet if I will continue working on this, but since this package looks currently abandoned, I believe that an update would not hurt anyway.

The `input_abstractions.jl` file probably should logically belong to another package, but since this package is its only user I don't see any reason not to keep it there for now. Its purpose it to abstract over XCB (and any system that sends input events, such as mouse/keyboard/joystick/pad) for input event handling. However IMHO it is too early to split something like this in a separate package, at least for now, even more so for just a small file.

### CODE REVIEW

**Comment by SimonDanisch** [comment]
Cool stuff! :) Let me know, once you think this is ready to go!

**Comment by serenity4** [comment]
Will do :)

**Comment by serenity4** [comment]
I think it is ready to be merged now. There might be some improvements to make later on, including having a documentation (only docstrings are present for now), but since I don't know when it will be done it should probably be a separate PR.
As for the tests, I am connecting to the X server, which currently fails on Travis CI. That would be something to look into at some point.

**Comment by TheCatster** [comment]
Is this ready to be merged? Would be absolutely phenomenal to have this updated.

**Comment by serenity4** [comment]
Yep, it certainly is enough for this PR which has become quite big already. @SimonDanisch  I think it could also be tagged for a new version.

**Comment by TheCatster** [comment]
Awesome! Yeah, agreed, been looking through the changes and 1.5 support alone would warrant a new version.

**Comment by SimonDanisch** [comment]
Cool! Btw, it'd be nice to keep this mostly low level, or little opinionated.. E.g., if I were to use this, I probably wouldn't want to use Rocket for the event handling. I actually happen to have some generic window abstractions I want to use across packages, so would be nice, if there is still a low level package that I can use, so that one won't need to fight against any other higher level layers ;) 
Note, that I probably won't do this any time soon, since I have 0 time for this, but just to keep it in the back of the minds, that other people may have other plans for this package :) 
I a bit of a barebone higher level API would be super welcome, though!

**Comment by serenity4** [comment]
Yes, you're right! Exposing a Julian API over XCB without adding extra-features unrelated to the core library would be more relevant for the package. I would absolutely love to have XCB.jl integrated into a window abstraction library, do you know of any? I wouldn't mind interfacing it in another PR. I think it would be great to have a cross-platform window library written in Julia that is lower level than GLFW and which selects the relevant window system for the user's platform.

**Comment by SimonDanisch** [comment]
Sounds great!

I'd love to factor out these files into a backend independent windowing event library:

https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/interaction/events.jl
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/interaction/iodevices.jl
https://github.com/JuliaPlots/AbstractPlotting.jl/blob/master/src/types.jl#L24

**Pull request merged**
